version: "3"

services:
  db:
    image: postgres
    env_file:
      - env-postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pconnection
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    networks:
      - pconnection
    depends_on:
      - "db"

volumes:
    pgdata:

networks:
  pconnection:
