# Generated by Django 3.0.6 on 2020-05-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
