# Generated by Django 3.0.6 on 2020-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
