# Generated by Django 3.0.6 on 2020-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('products', '0004_auto_20200520_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bills',
            field=models.ManyToManyField(to='bills.Bill'),
        ),
    ]
